

export function getServices(): string[] {
    return [
      "webdesign",
      "seo",
      "web-app"
    ];
  }

export function getBranches(): string[] {
    return [
      "elektriker",
      "gebeaudereinigung",
      "galabau",
      "hausmeisterservice"
    ];
  }



// Original Rohliste (Duplikate möglich) – interne Konstante
const rawCities = [
  // Großstädte und Städte (bestehende Liste)
  'Aach', 'Abensberg', 'Absberg', 'Bad Bramstedt', 'Bad Neuenahr-Ahrweiler',
  'Bad Soden am Taunus', 'Baesweiler', 'Baunatal', 'Bergen', 'Berlin',
  'Bestensee', 'Beverstedt', 'Bielefeld', 'Bonn', 'Brandenburg - Königs Wusterhausen',
  'Bremen', 'Buhl', 'Burghaslach', 'Bösel', 'Büttelborn', 'Celle', 'Coburg',
  'Coesfeld', 'Colbitz', 'Contwig', 'Detmold', 'Dillingen an der Donau',
  'Dorsten', 'Dortmund', 'Drolshagen', 'Düren', 'Düsseldorf', 'Ennepetal',
  'Erbach', 'Erftstadt', 'Erlangen', 'Eschweiler', 'Esslingen', 'Euskirchen',
  'Fehmarn', 'Fellbach', 'Filderstadt', 'Flensburg', 'Frankenthal',
  'Frankfurt am Main', 'Freiburg im Breisgau', 'Freising', 'Friedberg',
  'Friedrichshafen', 'Fürstenfeldbruck', 'Fürth', 'Garbsen', 'Gelsenkirchen',
  'Gera', 'Germersheim', 'Gießen', 'Gladbeck', 'Greifswald', 'Grevenbroich',
  'Gronau', 'Gummersbach', 'Gütersloh', 'Hagen', 'Halle', 'Hamburg',
  'Hameln', 'Hamm', 'Hanau', 'Hannover', 'Heidelberg', 'Heilbronn',
  'Herford', 'Herne', 'Herten', 'Hildesheim', 'Hofheim am Taunus',
  'Ingolstadt', 'Iserlohn', 'Jena', 'Kaiserslautern', 'Karlsruhe',
  'Kassel', 'Kempten', 'Kiel', 'Kleve', 'Koblenz', 'Köln', 'Konstanz',
  'Krefeld', 'Landshut', 'Langenfeld', 'Langenhagen', 'Leverkusen',
  'Limburg an der Lahn', 'Lippstadt', 'Ludwigsburg', 'Ludwigshafen am Rhein',
  'Lübeck', 'Lüdenscheid', 'Lüneburg', 'Magdeburg', 'Mainz', 'Marl',
  'Memmingen', 'Minden', 'Moers', 'Mönchengladbach', 'Mülheim an der Ruhr',
  'München', 'Münster', 'Neubrandenburg', 'Neumünster', 'Neuss',
  'Neuwied', 'Norderstedt', 'Northeim', 'Nürnberg', 'Offenbach am Main',
  'Offenburg', 'Oldenburg', 'Osnabrück', 'Paderborn', 'Passau',
  'Pforzheim', 'Pirmasens', 'Potsdam', 'Ravensburg', 'Recklinghausen',
  'Regensburg', 'Remscheid', 'Reutlingen', 'Rosenheim', 'Rostock',
  'Saarbrücken', 'Salzgitter', 'Schwäbisch Gmünd', 'Schwerin', 'Siegen',
  'Singen', 'Solingen', 'Stade', 'Stuttgart', 'Trier', 'Tübingen',
  'Ulm', 'Unna', 'Velbert', 'Viersen', 'Villingen-Schwenningen',
  'Wesel', 'Wetzlar', 'Wiesbaden', 'Wilhelmshaven', 'Witten', 'Wolfsburg',
  'Worms', 'Wuppertal', 'Würzburg', 'Zwickau',

  // Kleinstädte Deutschland (A-Z)
  'Aalen', 'Achern', 'Ahrensburg', 'Albstadt', 'Altena', 'Amberg', 'Andernach', 'Annaberg-Buchholz',
  'Ansbach', 'Apolda', 'Arnsberg', 'Arnstadt', 'Aschaffenburg', 'Augsburg', 'Aurich',
  'Backnang', 'Bad Aibling', 'Bad Berleburg', 'Bad Dürkheim', 'Bad Hersfeld', 'Bad Homburg',
  'Bad Kissingen', 'Bad Kreuznach', 'Bad Mergentheim', 'Bad Oeynhausen', 'Bad Oldesloe',
  'Bad Reichenhall', 'Bad Salzuflen', 'Bad Vilbel', 'Bad Zwischenahn', 'Bamberg', 'Bautzen',
  'Bayreuth', 'Beckum', 'Bergheim', 'Bergisch Gladbach', 'Bergneustadt', 'Bernburg', 'Biberach',
  'Bietigheim-Bissingen', 'Blankenburg', 'Blieskastel', 'Blomberg', 'Bornheim', 'Bottrop',
  'Brandenburg an der Havel', 'Braunschweig', 'Brilon', 'Bruchsal', 'Brühl', 'Büdingen',
  'Bünde', 'Burg', 'Burgdorf', 'Calw', 'Castrop-Rauxel', 'Cham', 'Chemnitz', 'Cloppenburg',
  'Cottbus', 'Crailsheim', 'Cuxhaven', 'Dachau', 'Darmstadt', 'Deggendorf', 'Delmenhorst',
  'Dessau-Roßlau', 'Dietzenbach', 'Dillenburg', 'Dinkelsbühl', 'Ditzingen', 'Döbeln',
  'Donaueschingen', 'Dormagen', 'Dresden', 'Duderstadt', 'Duisburg', 'Eberswalde', 'Eckernförde',
  'Ehingen', 'Einbeck', 'Eisenach', 'Eisenhüttenstadt', 'Eislingen', 'Ellwangen', 'Elmshorn',
  'Emden', 'Emmendingen', 'Emsdetten', 'Erding', 'Erfurt', 'Erkrath', 'Erwitte', 'Essen',
  'Ettlingen', 'Eutin', 'Falkensee', 'Falkenstein', 'Feuchtwangen', 'Finsterwalde', 'Forchheim',
  'Forst', 'Frechen', 'Freiberg', 'Freudenstadt', 'Freyung', 'Friedrichsdorf', 'Fulda',
  'Füssen', 'Gaggenau', 'Garmisch-Partenkirchen', 'Gauting', 'Geesthacht', 'Geilenkirchen',
  'Geislingen', 'Geldern', 'Gelnhausen', 'Genthin', 'Georgsmarienhutte', 'Geretsried',
  'Gevelsberg', 'Gifhorn', 'Ginsheim-Gustavsburg', 'Glauchau', 'Goch', 'Göppingen',
  'Görlitz', 'Goslar', 'Gotha', 'Göttingen', 'Grafing', 'Greven', 'Grimma', 'Grünberg',
  'Grünstadt', 'Güstrow', 'Haan', 'Hagenow', 'Halberstadt', 'Haltern am See', 'Hameln',
  'Hamminkeln', 'Hanau', 'Harburg', 'Hardegsen', 'Haslach', 'Haßfurt', 'Hattersheim',
  'Hattingen', 'Hausach', 'Heide', 'Heidenheim', 'Heinsberg', 'Helmstedt', 'Hemer',
  'Hennef', 'Henstedt-Ulzburg', 'Heppenheim', 'Herzberg', 'Herzogenaurach', 'Hessisch Lichtenau',
  'Hilden', 'Hockenheim', 'Hof', 'Hohen Neuendorf', 'Holzminden', 'Homburg', 'Horb',
  'Höxter', 'Hoyerswerda', 'Hückelhoven', 'Hürth', 'Husum', 'Ibbenbüren', 'Idar-Oberstein',
  'Ilmenau', 'Ingelheim', 'Ingolstadt', 'Isny', 'Jülich', 'Kaarst', 'Kahla', 'Kamenz',
  'Karlsfeld', 'Kaufbeuren', 'Kehl', 'Kelkheim', 'Kempen', 'Kenzingen', 'Kerpen', 'Kitzingen',
  'Kornwestheim', 'Korschenbroich', 'Königswinter', 'Künzelsau', 'Lahr', 'Lampertheim',
  'Landau', 'Langen', 'Langenau', 'Lauchhammer', 'Lauf', 'Laupheim', 'Leer', 'Leichlingen',
  'Leinefelde-Worbis', 'Lemgo', 'Lennestadt', 'Leonberg', 'Leutkirch', 'Lich', 'Lichtenfels',
  'Lindau', 'Lingen', 'Lohmar', 'Löhne', 'Lohne', 'Lohr', 'Luckenwalde', 'Ludwigsfelde',
  'Lychen', 'Magdeburg', 'Mannheim', 'Marburg', 'Markgröningen', 'Marktoberdorf', 'Marktredwitz',
  'Mayen', 'Mechernich', 'Meinerzhagen', 'Meiningen', 'Meißen', 'Melle', 'Memmingen',
  'Menden', 'Merseburg', 'Mettmann', 'Miesbach', 'Miltenberg', 'Mittweida', 'Möhnesee',
  'Monheim', 'Moormerland', 'Mosbach', 'Mühlacker', 'Mühlhausen', 'Mühldorf', 'Müllheim',
  'Münchberg', 'Münchenbernsdorf', 'Munster', 'Murrhardt', 'Nauen', 'Naumburg', 'Neckarsulm',
  'Netphen', 'Nettetal', 'Neu-Anspach', 'Neu-Isenburg', 'Neu-Ulm', 'Neuburg', 'Neumarkt',
  'Neuötting', 'Neuruppin', 'Neusäß', 'Neustadt', 'Nienburg', 'Norden', 'Nordenham',
  'Nordhausen', 'Nordhorn', 'Nürtingen', 'Oberasbach', 'Oberhausen', 'Obernburg', 'Ochtrup',
  'Oelde', 'Oer-Erkenschwick', 'Offenburg', 'Öhringen', 'Olpe', 'Osterholz-Scharmbeck',
  'Osterode', 'Ottobrunn', 'Overath', 'Parchim', 'Peine', 'Petershagen', 'Pfaffenhofen',
  'Pfullingen', 'Pinneberg', 'Plauen', 'Plettenberg', 'Pockau', 'Porta Westfalica',
  'Prenzlau', 'Pulheim', 'Quickborn', 'Radolfzell', 'Rathenow', 'Ratingen', 'Ravensburg',
  'Rees', 'Rendsburg', 'Rheda-Wiedenbrück', 'Rheine', 'Rheinbach', 'Rheinberg', 'Rheinböllen',
  'Rheinfelden', 'Rheinstetten', 'Riesa', 'Rietberg', 'Rinteln', 'Rodgau', 'Rohrbach',
  'Ronnenberg', 'Rosengarten', 'Roth', 'Rotenburg', 'Rottenburg', 'Rottweil', 'Rudolstadt',
  'Saalfeld', 'Saarlouis', 'Sachsenheim', 'Salzwedel', 'Sankt Augustin', 'Sankt Georgen',
  'Sankt Ingbert', 'Sankt Wendel', 'Schifferstadt', 'Schkeuditz', 'Schleswig', 'Schmalkalden',
  'Schmallenberg', 'Schönebeck', 'Schönefeld', 'Schönwald', 'Schopfheim', 'Schorndorf',
  'Schramberg', 'Schrobenhausen', 'Schwabach', 'Schwäbisch Hall', 'Schwalmstadt', 'Schwandorf',
  'Schwarzenberg', 'Schwedt', 'Schwelm', 'Schwerte', 'Seelze', 'Seesen', 'Senden', 'Siegburg',
  'Sigmaringen', 'Sindelfingen', 'Sinsheim', 'Soltau', 'Sömmerda', 'Sonneberg', 'Speyer',
  'Springe', 'Starnberg', 'Staßfurt', 'Steinfurt', 'Steinhagen', 'Stellingen', 'Stolberg',
  'Stralsund', 'Straubing', 'Strausberg', 'Stuhr', 'Suhl', 'Sundern', 'Syke', 'Taunusstein',
  'Telgte', 'Templin', 'Tettnang', 'Thale', 'Tönisvorst', 'Traunreut', 'Traunstein',
  'Troisdorf', 'Tübingen', 'Tuttlingen', 'Überlingen', 'Uetze', 'Uhingen', 'Ulm', 'Unkel',
  'Unterhaching', 'Unterschleißheim', 'Vaihingen', 'Vechta', 'Velden', 'Velten', 'Verden',
  'Versmold', 'Viechtach', 'Vilsbiburg', 'Vilshofen', 'Völklingen', 'Vreden', 'Wachtberg',
  'Waghäusel', 'Waiblingen', 'Waldkraiburg', 'Waldshut-Tiengen', 'Wangen', 'Warburg',
  'Waren', 'Warstein', 'Wasserburg', 'Weiden', 'Weil am Rhein', 'Weilheim', 'Weimar',
  'Weinheim', 'Weinstadt', 'Weißenfels', 'Weiterstadt', 'Wels', 'Wenden', 'Werder',
  'Werdohl', 'Werne', 'Wernigerode', 'Wertheim', 'Wesseling', 'Westerstede', 'Wetter',
  'Wetzlar', 'Weyhe', 'Wiedenbrück', 'Wiehl', 'Wildeshausen', 'Winnenden', 'Winsen',
  'Wipperfürth', 'Wismar', 'Wittenberg', 'Wittlich', 'Wittmund', 'Wolfenbüttel',
  'Wolmirstedt', 'Worms', 'Xanten', 'Zeitz', 'Zerbst', 'Zirndorf', 'Zittau', 'Zweibrücken',

  // Weitere deutsche Städte und Gemeinden
  'Abentheuer', 'Achim', 'Adenau', 'Adorf', 'Ahaus', 'Ahlen', 'Aichach', 'Aidenbach',
  'Aken', 'Alfeld', 'Allendorf', 'Alsdorf', 'Altdorf', 'Altenkirchen', 'Altensteig', 'Altötting',
  'Alzey', 'Amöneburg', 'Anklam', 'Annweiler', 'Apolda', 'Arnschwang', 'Ascheberg', 'Attendorn',
  'Aue', 'Aulendorf', 'Bad Abbach', 'Bad Arolsen', 'Bad Belzig', 'Bad Bentheim', 'Bad Bergzabern',
  'Bad Bevensen', 'Bad Brückenau', 'Bad Buchau', 'Bad Camberg', 'Bad Doberan', 'Bad Driburg',
  'Bad Ems', 'Bad Fallingbostel', 'Bad Friedrichshall', 'Bad Gandersheim', 'Bad Harzburg',
  'Bad Honnef', 'Bad Karlshafen', 'Bad Laasphe', 'Bad Lauterberg', 'Bad Liebenzell', 'Bad Lippspringe',
  'Bad Marienberg', 'Bad Münder', 'Bad Münstereifel', 'Bad Nauheim', 'Bad Nenndorf', 'Bad Neustadt',
  'Bad Orb', 'Bad Pyrmont', 'Bad Rappenau', 'Bad Saulgau', 'Bad Schwalbach', 'Bad Segeberg',
  'Bad Sooden-Allendorf', 'Bad Tölz', 'Bad Urach', 'Bad Waldsee', 'Bad Wildungen', 'Bad Windsheim',
  'Bad Wörishofen', 'Balingen', 'Barntrup', 'Barsinghausen', 'Barth', 'Bassum', 'Battenberg',
  'Bautzen', 'Bebra', 'Bechhofen', 'Bedburg', 'Beelitz', 'Belgern', 'Bendorf', 'Berching',
  'Berka', 'Bernau', 'Bernkastel-Kues', 'Bernsdorf', 'Besigheim', 'Betzdorf', 'Bexbach',
  'Biedenkopf', 'Billerbeck', 'Bingen', 'Birkenfeld', 'Bischofsheim', 'Bitterfeld', 'Blaubeuren',
  'Bleckede', 'Blomberg', 'Bocholt', 'Bodelshausen', 'Böblingen', 'Bönnigheim', 'Bopfingen',
  'Brakel', 'Brake', 'Bramsche', 'Brand-Erbisdorf', 'Brandis', 'Braunlage', 'Bredstedt',
  'Breisach', 'Bremerhaven', 'Bremervörde', 'Bretten', 'Brilon', 'Broichweiden', 'Brüggen',
  'Brunsbüttel', 'Buchen', 'Buchholz', 'Buckow', 'Büdingen', 'Bühl', 'Bulle', 'Bunde',
  'Burghausen', 'Burgkunstadt', 'Burglengenfeld', 'Burgwedel', 'Burladingen', 'Butzbach',
  'Calbe', 'Calvörde', 'Camburg', 'Castle', 'Clausthal-Zellerfeld', 'Coesfeld', 'Coswig',
  'Crimmitschau', 'Crivitz', 'Dahn', 'Damme', 'Dannenberg', 'Dargun', 'Dassow', 'Daun',
  'Deidesheim', 'Delbrück', 'Demmin', 'Dettelbach', 'Dieburg', 'Diemelstadt', 'Diepholz',
  'Dierdorf', 'Dietfurt', 'Diez', 'Dippoldiswalde', 'Dissen', 'Ditzingen', 'Dohna',
  'Dollern', 'Donauworth', 'Donzdorf', 'Dörpen', 'Dransfeld', 'Dreieich', 'Drensteinfurt',
  'Drolshagen', 'Duderstadt', 'Dülmen', 'Düren', 'Durbach', 'Eberbach', 'Ebermannstadt',
  'Ebern', 'Ebersberg', 'Eching', 'Eckernförde', 'Edenkoben', 'Egeln', 'Eggenfelden',
  'Eichstätt', 'Eilenburg', 'Einbeck', 'Eisfeld', 'Eislingen', 'Ellingen', 'Ellrich',
  'Elsdorf', 'Elsterwerda', 'Eltville', 'Elze', 'Emmendingen', 'Engen', 'Ennigerloh',
  'Eppingen', 'Eppstein', 'Erbach', 'Erding', 'Ergolding', 'Erkner', 'Erlensee', 'Erndtebrück',
  'Eschborn', 'Eschenbach', 'Eschershausen', 'Eschwege', 'Espelkamp', 'Essen', 'Ettenheim',
  'Euerdorf', 'Euskirchen', 'Extertal', 'Falkenberg', 'Fehmarn', 'Feldberg', 'Felsberg',
  'Feucht', 'Fichtelberg', 'Filderstadt', 'Finsterwalde', 'Fladungen', 'Flöha', 'Flörsheim',
  'Floß', 'Forbach', 'Forchtenberg', 'Frankenberg', 'Frauenau', 'Freystadt', 'Fridingen',
  'Frielendorf', 'Friesoythe', 'Fritzlar', 'Fröndenberg', 'Fürstenberg', 'Fürstenwalde',
  'Furth', 'Furtwangen', 'Gadebusch', 'Gaildorf', 'Gammertingen', 'Garching', 'Gardelegen',
  'Garding', 'Gau-Algesheim', 'Gedern', 'Geisa', 'Geisenfeld', 'Geisenheim', 'Geithain',
  'Gelnhausen', 'Gemünden', 'Gengenbach', 'Georgsmarienhütte', 'Gera', 'Gerlingen', 'Germering',
  'Gernsbach', 'Gernsheim', 'Gescher', 'Geseke', 'Gevelsberg', 'Geyer', 'Giengen', 'Gifhorn',
  'Gladenbach', 'Glauchau', 'Glinde', 'Glücksburg', 'Glückstadt', 'Gnoien', 'Goch',
  'Goldberg', 'Goldkronach', 'Golßen', 'Gomaringen', 'Gosheim', 'Gottenheim', 'Grabow',
  'Gräfenberg', 'Gräfenhainichen', 'Gransee', 'Greding', 'Greiz', 'Grenzach-Wyhlen',
  'Grevesmühlen', 'Grevenbroich', 'Grimmen', 'Gröditz', 'Groitzsch', 'Gromitz', 'Großbothen',
  'Großenhain', 'Großröhrsdorf', 'Grünhain', 'Grünstadt', 'Guben', 'Güglingen', 'Gundelfingen',
  'Gunzenhausen', 'Gustow', 'Haan', 'Hachenburg', 'Hadamar', 'Hagenbach', 'Haiger', 'Hainichen',
  'Hallbergmoos', 'Hallein', 'Halver', 'Hambergen', 'Hamelburg', 'Hammelburg', 'Hangelsberg',
  'Harsewinkel', 'Haselünne', 'Haßloch', 'Hattersheim', 'Hatzfeld', 'Hausham', 'Hayingen',
  'Hechingen', 'Heddesheim', 'Heide', 'Heideck', 'Heidenau', 'Heiligenhafen', 'Heiligenhaus',
  'Heimsheim', 'Heinsberg', 'Helmbrechts', 'Helpsen', 'Hemer', 'Hemsbach', 'Hennigsdorf',
  'Heppenheim', 'Herbrechtingen', 'Herbstein', 'Herdecke', 'Herdorf', 'Herford', 'Herleshausen',
  'Hermeskeil', 'Herrenberg', 'Herrieden', 'Herscheid', 'Herzberg', 'Herzogenrath', 'Hessisch Oldendorf',
  'Hettstedt', 'Heubach', 'Heusenstamm', 'Hilchenbach', 'Hilpoltstein', 'Hiltrup', 'Hirschaid',
  'Hirschberg', 'Hirschhorn', 'Hitzacker', 'Höchberg', 'Höchstadt', 'Hockenheim', 'Hodenhagen',
  'Hohenems', 'Hohenfels', 'Hohenleuben', 'Hohenlohe', 'Hohenpeißenberg', 'Hohenstein-Ernstthal',
  'Höhr-Grenzhausen', 'Hollabrunn', 'Holzgerlingen', 'Holzheim', 'Holzkirchen', 'Homberg',
  'Hopsten', 'Horgau', 'Horka', 'Hornburg', 'Horneb', 'Hösbach', 'Hückelhoven', 'Hude',
  'Hünfeld', 'Hungen', 'Huntlosen', 'Hürth', 'Hutthurm', 'Ichenhausen', 'Idstein', 'Iffezheim',
  'Illingen', 'Illertissen', 'Immenstadt', 'Inchenhofen', 'Ingelfingen', 'Ingelheim', 'Iphofen',
  'Isernhagen', 'Isselburg', 'Itzehoe', 'Jandelsbrunn', 'Jarmen', 'Jessen', 'Joachimsthal',
  'Jöhstadt', 'Jüchen', 'Jüterbog', 'Kahl', 'Kahla', 'Kalkar', 'Kamen', 'Kandel',
  'Kandern', 'Kappeln', 'Karben', 'Karlstadt', 'Kassel', 'Kastl', 'Katzenelnbogen', 'Kaulsdorf',
  'Kayna', 'Kehrig', 'Kelbra', 'Kelheim', 'Kelsterbach', 'Kemberg', 'Kempen', 'Kenzingen',
  'Kernen', 'Kettwig', 'Ketzin', 'Kevelaer', 'Kierspe', 'Kinding', 'Kippenheim', 'Kirchberg',
  'Kirchdorf', 'Kirchenlamitz', 'Kirchheimbolanden', 'Kirchhundem', 'Kirchweidach', 'Kirn',
  'Kirtorf', 'Kitzscher', 'Klötze', 'Knittlingen', 'Knüllwald', 'Kölleda', 'Königs Wusterhausen',
  'Königsbach-Stein', 'Königsbrunn', 'Königsee', 'Königslutter', 'Königstein', 'Konz',
  'Korbach', 'Korntal-Münchingen', 'Köthen', 'Kraichtal', 'Kraiburg', 'Kranenburg', 'Krauchenwies',
  'Krautheim', 'Kreuztal', 'Kronach', 'Kronberg', 'Krumbach', 'Kulmbach', 'Künzell', 'Kuppenheim',
  'Küps', 'Kyritz', 'Laaber', 'Ladenburg', 'Lage', 'Lahnstein', 'Lahr', 'Lam',
  'Lambrecht', 'Landsberg', 'Langelsheim', 'Langenau', 'Langenbrettach', 'Langendorf', 'Langenselbold',
  'Langeoog', 'Langquaid', 'Langwedel', 'Lauf', 'Laufen', 'Laufenburg', 'Lauingen', 'Lauterbach',
  'Lauterecken', 'Lauter-Bernsbach', 'Lebach', 'Lebus', 'Leer', 'Lehre', 'Leichlingen', 'Leimen',
  'Leisnig', 'Lenting', 'Leonberg', 'Leuna', 'Leutershausen', 'Lichtenberg', 'Lichtenstein',
  'Liebenau', 'Liebenwalde', 'Lieser', 'Limbach', 'Lindenberg', 'Lindenfels', 'Linkenheim',
  'Lippetal', 'Löbau', 'Löffingen', 'Lohfelden', 'Lohne', 'Loitz', 'Lollar', 'Lommatzsch',
  'Lorch', 'Lörrach', 'Lörzweiler', 'Losheim', 'Löwenstein', 'Lübben', 'Lübbenau', 'Lübtheen',
  'Lübz', 'Lucka', 'Lüchow', 'Lüdenscheid', 'Ludwigslust', 'Lugau', 'Lügde', 'Lünne',
  'Lütjenburg', 'Lützen', 'Lychen',

  // Weitere deutsche Städte und Gemeinden (M-Z) um auf 1000 zu kommen
  'Mackensen', 'Magstadt', 'Malchin', 'Malente', 'Mallersdorf-Pfaffenberg', 'Malsch', 'Manderscheid',
  'Marbach', 'Marienheide', 'Marienmünster', 'Markkleeberg', 'Marktbreit', 'Marktgraitz', 'Marktheidenfeld',
  'Marktleuthen', 'Marktschellenberg', 'Marktsteft', 'Maroldsweisach', 'Marxzell', 'Massing',
  'Maxhütte-Haidhof', 'Maxsain', 'Meckenbeuren', 'Meerbusch', 'Meerane', 'Mehltheuer', 'Meisenheim',
  'Mellrichstadt', 'Melsungen', 'Menden', 'Mengerskirchen', 'Mengen', 'Meppen', 'Merenberg',
  'Merkendorf', 'Merzig', 'Meschede', 'Messstetten', 'Mettingen', 'Metzingen', 'Michelstadt',
  'Miesbach', 'Milbertshofen', 'Mindelheim', 'Mittelbiberach', 'Mitterfels', 'Mitterskirchen',
  'Mittenwald', 'Möckmühl', 'Mögglingen', 'Mölln', 'Mömlingen', 'Monschau', 'Montabaur',
  'Moosburg', 'Moosbach', 'Moringen', 'Morsbach', 'Mörz', 'Mosbach', 'Mudau', 'Mügeln',
  'Mühlberg', 'Mühlenbecker Land', 'Mühltal', 'Mülheim-Kärlich', 'Müllrose', 'Münnerstadt',
  'Münzenberg', 'Murrhardt', 'Nabburg', 'Nagold', 'Naila', 'Nassau', 'Nastätten', 'Naumburg',
  'Nebra', 'Neckargemünd', 'Neckartenzlingen', 'Neckartailfingen', 'Neckarsteinach', 'Neenah',
  'Nentershausen', 'Nersingen', 'Nesselwang', 'Nettetal', 'Neubiberg', 'Neuburg am Inn',
  'Neudenau', 'Neudrossenfeld', 'Neuenhaus', 'Neuenrade', 'Neuenstein', 'Neuerburg', 'Neufahrn',
  'Neuhausen', 'Neuhof', 'Neukirchen', 'Neukirchen-Vluyn', 'Neulußheim', 'Neumarkt-Sankt Veit',
  'Neumühle', 'Neunburg vorm Wald', 'Neunkirchen', 'Neustrelitz', 'Neutrebbin', 'Newel',
  'Nidda', 'Niddatal', 'Nidderau', 'Nideggen', 'Niebuell', 'Niedenstein', 'Niederau',
  'Niederkassel', 'Niedernhall', 'Niederstetten', 'Nieheim', 'Niemegk', 'Niesky', 'Nittenau',
  'Nördlingen', 'Nordharz', 'Nordlingen', 'Northeim', 'Nottuln', 'Nümbrecht', 'Nußloch',
  'Oberammergau', 'Oberderdingen', 'Oberdischingen', 'Oberding', 'Oberdorf', 'Oberelsbach',
  'Obergurig', 'Oberhaid', 'Oberkirch', 'Oberkochen', 'Oberland', 'Obermoschel', 'Obernai',
  'Obernburg', 'Oberndorf', 'Oberpleis', 'Oberreichenbach', 'Oberriexingen', 'Oberstaufen',
  'Oberstdorf', 'Oberteuringen', 'Obertshausen', 'Oberursel', 'Oberviechtach', 'Oberwesel',
  'Obing', 'Ochsenfurt', 'Ochsenhausen', 'Oderberg', 'Oebisfelde', 'Oehringen', 'Oelde',
  'Oelsnitz', 'Oerlinghausen', 'Oestrich-Winkel', 'Ofterdingen', 'Olbernhau', 'Olching',
  'Oldendorf', 'Olfen', 'Olsberg', 'Oppenau', 'Oppenheim', 'Oranienbaum', 'Oranienburg',
  'Orchideen', 'Ornbau', 'Ortenberg', 'Ortrand', 'Oschatz', 'Oschersleben', 'Osterburg',
  'Osterfeld', 'Ostfildern', 'Ostheim', 'Osthofen', 'Otterbach', 'Otterndorf', 'Ottersberg',
  'Ottweiler', 'Owen', 'Oybin', 'Paderborn', 'Papenburg', 'Pappenheim', 'Parsberg', 'Pasewalk',
  'Passau', 'Pattensen', 'Pausa', 'Pegau', 'Pegnitz', 'Peine', 'Penig', 'Penzberg',
  'Penzlin', 'Perleberg', 'Petershagen', 'Pfaffenhofen', 'Pfarrkirchen', 'Pforzheim', 'Pfreimd',
  'Pfronten', 'Pfullendorf', 'Pfullingen', 'Philippsburg', 'Piding', 'Pielenhofen', 'Pinneberg',
  'Pirna', 'Planegg', 'Plau am See', 'Pleinfeld', 'Pleystein', 'Plochingen', 'Plön',
  'Pocking', 'Pöcking', 'Pößneck', 'Polch', 'Pollnow', 'Pommersfelden', 'Poppenricht',
  'Poppenhausen', 'Porta Westfalica', 'Pottenstein', 'Preetz', 'Premnitz', 'Pressath',
  'Preußisch Oldendorf', 'Prichsenstadt', 'Pritzwalk', 'Prüm', 'Puchheim', 'Pulsnitz',
  'Putbus', 'Putlitz', 'Pyrbaum', 'Quakenbrück', 'Quedlinburg', 'Querfurt', 'Quickborn',
  'Rabenau', 'Radeberg', 'Radebeul', 'Radeburg', 'Radeformwald', 'Radolfzell', 'Rahden',
  'Rain', 'Ramstein-Miesenbach', 'Rangsdorf', 'Ransbach-Baumbach', 'Rastatt', 'Rastede',
  'Ratekau', 'Rauenberg', 'Rauschenberg', 'Ravenstein', 'Rees', 'Regen', 'Regenstauf',
  'Rehau', 'Rehburg-Loccum', 'Rehna', 'Reichelsheim', 'Reichenbach', 'Reilingen', 'Reimlingen',
  'Reinbek', 'Reinfeld', 'Reinheim', 'Reinsfeld', 'Rellingen', 'Remagen', 'Renchen',
  'Rennerod', 'Renningen', 'Rerik', 'Rethem', 'Rhauderfehn', 'Rheinau', 'Rheinböllen',
  'Rheinbreitbach', 'Rheine', 'Rheinfelden', 'Rheinmünster', 'Rheinstetten', 'Ribnitz-Damgarten',
  'Rickenbach', 'Riedenburg', 'Riedstadt', 'Riegel', 'Rieneck', 'Riesa', 'Rietberg',
  'Rimbach', 'Rimpar', 'Rinchnach', 'Rinteln', 'Ritterhude', 'Röbel', 'Rochlitz', 'Rödermark',
  'Rödersee', 'Rödinghausen', 'Roding', 'Roggenburg', 'Rohr', 'Rohrbach', 'Röhrmoos',
  'Römhild', 'Ronneburg', 'Rosbach', 'Röslau', 'Rossau', 'Rossdorf', 'Röthenbach',
  'Rothenburg ob der Tauber', 'Röthlein', 'Rott', 'Rottach-Egern', 'Röttingen', 'Rötz',
  'Rückersdorf', 'Rüdesheim', 'Rudolstadt', 'Ruhla', 'Ruhstorf', 'Runkel', 'Rüsselsheim',
  'Rutesheim', 'Rüthen', 'Saalburg-Ebersdorf', 'Saarburg', 'Saarwellingen', 'Sachsenheim',
  'Sailauf', 'Salach', 'Salem', 'Salzhausen', 'Salzwedel', 'Sandau', 'Sandersdorf',
  'Sangerhausen', 'Sankt Blasien', 'Sankt Goar', 'Sankt Goarshausen', 'Sankt Leon-Rot',
  'Sankt Märgen', 'Sankt Peter-Ording', 'Sarstedt', 'Sassenburg', 'Sassnitz', 'Sayda',
  'Schalkau', 'Schallstadt', 'Scharbeutz', 'Scharfenstein', 'Schauenburg', 'Scheer',
  'Scheeßel', 'Schefflenz', 'Scheinfeld', 'Schelklingen', 'Schenefeld', 'Schenkenzell',
  'Scheßlitz', 'Scheyern', 'Schieder-Schwalenberg', 'Schiffdorf', 'Schillingsfürst',
  'Schiltach', 'Schimberg', 'Schirgiswalde', 'Schkeuditz', 'Schleiz', 'Schliersee',
  'Schlitz', 'Schloß Holte-Stukenbrock', 'Schlüchtern', 'Schlüsselfeld', 'Schmalkalden',
  'Schmannewitz', 'Schmidmühlen', 'Schmölln', 'Schnackenburg', 'Schnaittenbach', 'Schneeberg',
  'Schneverdingen', 'Schömberg', 'Schonach', 'Schönau', 'Schönberg', 'Schönbrunn',
  'Schöndorf', 'Schöneck', 'Schöningen', 'Schöntal', 'Schönwald', 'Schopfloch', 'Schöppingen',
  'Schotten', 'Schramberg', 'Schrecksbach', 'Schrobenhausen', 'Schrozberg', 'Schüttorf',
  'Schutterwald', 'Schwaigern', 'Schwalbach', 'Schwalmtal', 'Schwanau', 'Schwandorf',
  'Schwarzach', 'Schwarzburg', 'Schwarzenbach', 'Schwarzenborn', 'Schwarzheide', 'Schweich',
  'Schweinfurt', 'Schwentinental', 'Schwetzingen', 'Schwielowsee', 'Sebnitz', 'Seckach',
  'Seehausen', 'Seeheim-Jugenheim', 'Seekirch', 'Seelbach', 'Seesen', 'Seiffen', 'Selb',
  'Selbitz', 'Seligenstadt', 'Selm', 'Senden', 'Sendenhorst', 'Senftenberg', 'Sessenhausen',
  'Sigmaringendorf', 'Simbach', 'Simmerath', 'Sindelfingen', 'Singen', 'Sinntal', 'Sinzig',
  'Söchtenau', 'Soest', 'Sohland', 'Solms', 'Soltau', 'Sömmerda', 'Sondershausen', 'Sonnefeld',
  'Sonnenstein', 'Sonsbeck', 'Sontheim', 'Sonthofen', 'Sosa', 'Spalt', 'Spangenberg',
  'Sparneck', 'Spay', 'Speichersdorf', 'Spelle', 'Spenge', 'Spiegelau', 'Spiesheim',
  'Sprockhövel', 'Stade', 'Stadtallendorf', 'Stadtbergen', 'Stadthagen', 'Stadtilm',
  'Stadtlauringen', 'Stadtoldendorf', 'Stadtprozelten', 'Stadtroda', 'Stadtsteinach',
  'Stamsried', 'Starnberg', 'Staufen', 'Stavenhagen', 'Steimbke', 'Steinach', 'Steinau',
  'Steinbach', 'Steinberg', 'Steinen', 'Steinfeld', 'Steingaden', 'Steinheim', 'Steinhorst',
  'Stendal', 'Stephanskirchen', 'Sternberg', 'Stockach', 'Stockstadt', 'Stollberg',
  'Stolpen', 'Storkow', 'Stößen', 'Strausberg', 'Strullendorf', 'Stutensee', 'Sulingen',
  'Sulz', 'Sulzbach', 'Sulzbach-Rosenberg', 'Sulzberg', 'Sulzburg', 'Sulzfeld', 'Sundern',
  'Süßen', 'Syke', 'Tambach-Dietharz', 'Tangerhütte', 'Tangermünde', 'Tann', 'Tanna',
  'Taufkirchen', 'Taunusstein', 'Tecklenburg', 'Tegernsee', 'Telgte', 'Teltow', 'Templin',
  'Tengen', 'Tessin', 'Teterow', 'Tettnang', 'Teublitz', 'Teuchern', 'Teunz', 'Thale',
  'Thalheim', 'Thallichtenberg', 'Thanstein', 'Themar', 'Thierhaupten', 'Thiersheim',
  'Thum', 'Thurmansbang', 'Timmendorfer Strand', 'Tirschenreuth', 'Titisee-Neustadt',
  'Todtnau', 'Töging', 'Tönning', 'Torgelow', 'Tornesch', 'Traben-Trarbach', 'Trebbin',
  'Trebur', 'Trendelburg', 'Treuchtlingen', 'Treuen', 'Triberg', 'Triefenstein', 'Triftern',
  'Trochtelfingen', 'Tröstau', 'Trostberg', 'Tübingen', 'Tuttlingen', 'Twist', 'Überherrn',
  'Uebigau', 'Uedem', 'Uetersen', 'Uffenheim', 'Uhldingen-Mühlhofen', 'Uhlstädt',
  'Ulmen', 'Ummerstadt', 'Unkel', 'Unna', 'Unstruttal', 'Unterföhring', 'Untergruppenbach',
  'Unterhaching', 'Unterschleißheim', 'Usingen', 'Uslar', 'Uttenreuth', 'Vacha', 'Vaihingen',
  'Vallendar', 'Varel', 'Vaterstetten', 'Vechelde', 'Velen', 'Velten', 'Venusberg',
  'Verden', 'Veringenstadt', 'Verl', 'Versmold', 'Vetschau', 'Viechtach', 'Vienenburg',
  'Viernheim', 'Villingen-Schwenningen', 'Vilsbiburg', 'Vilseck', 'Vilshofen', 'Visbek',
  'Visselhövede', 'Voerde', 'Vohenstrauß', 'Vohburg', 'Volkach', 'Volkmarsen', 'Völklingen',
  'Vollersode', 'Vöhrenbach', 'Vöhringen', 'Vreden', 'Wachenheim', 'Wächtersbach',
  'Wadgassen', 'Wadern', 'Waghäusel', 'Wahlstedt', 'Waibstadt', 'Waidhaus', 'Waischenfeld',
  'Waldbröl', 'Waldeck', 'Waldfeucht', 'Waldkappel', 'Waldkirch', 'Waldkraiburg', 'Waldmünchen',
  'Waldsassen', 'Waldshut-Tiengen', 'Wallenhorst', 'Wallerfangen', 'Wallgau', 'Waltershausen',
  'Waltrop', 'Wangen', 'Wankendorf', 'Wanfried', 'Warburg', 'Waren', 'Warin', 'Warnemünde',
  'Wartenberg', 'Wasserburg', 'Wassertrüdingen', 'Waststetten', 'Wathlingen', 'Weener',
  'Wegberg', 'Wehr', 'Weichs', 'Weiden', 'Weidhausen', 'Weidenberg', 'Weikersheim',
  'Weil der Stadt', 'Weilburg', 'Weilheim', 'Weimar', 'Weinböhla', 'Weingarten', 'Weinheim',
  'Weinsberg', 'Weinstadt', 'Weismain', 'Weißenborn', 'Weißenburg', 'Weißenhorn', 'Weißenstadt',
  'Weißwasser', 'Weixdorf', 'Welzheim', 'Wemding', 'Wendeburg', 'Wendlingen', 'Wennigsen',
  'Werbach', 'Werdau', 'Werder', 'Wernau', 'Werne', 'Werneuchen', 'Wernigerode', 'Wernshausen',
  'Wertach', 'Werther', 'Wertingen', 'Wesel', 'Wesenberg', 'Wesselburen', 'Wesseling',
  'Westendorf', 'Westerburg', 'Westerstede', 'Westoverledingen', 'Wetter', 'Wettin',
  'Wetzlar', 'Weyhe', 'Weyhausen', 'Wickede', 'Wiefelstede', 'Wiehl', 'Wielenbach',
  'Wieren', 'Wiesbaden', 'Wiesenburg', 'Wiesloch', 'Wietmarschen', 'Wietze', 'Wildau',
  'Wildberg', 'Wildenfels', 'Wildeshausen', 'Wildflecken', 'Wilhelmsburg', 'Wilkau-Haßlau',
  'Willebadessen', 'Willich', 'Wilsdruff', 'Wilster', 'Wilthen', 'Windeck', 'Windsbach',
  'Winnenden', 'Winsen', 'Winterbach', 'Winterberg', 'Wipperfürth', 'Wirges', 'Wischhafen',
  'Wismar', 'Wittdün', 'Wittenberg', 'Wittenberge', 'Wittingen', 'Wittlich', 'Wittmund',
  'Wittstock', 'Witzenhausen', 'Wölfersheim', 'Wolfhagen', 'Wolframs-Eschenbach', 'Wolfratshausen',
  'Wolfsburg', 'Wolfstein', 'Wolgast', 'Wolmirstedt', 'Worms', 'Wörth', 'Wunsiedel',
  'Wunstorf', 'Wuppertal', 'Würselen', 'Würzburg', 'Wüstenrot', 'Wustrow', 'Wyk auf Föhr',
  'Xanten', 'Zabeltitz', 'Zehdenick', 'Zeitz', 'Zell', 'Zella-Mehlis', 'Zerbst',
  'Zeulenroda', 'Zeven', 'Ziegenrück', 'Zierenberg', 'Zirndorf', 'Zittau', 'Zossen',
  'Zörbig', 'Zorneding', 'Zschopau', 'Zülpich', 'Zweibrücken', 'Zweiflingen', 'Zwenkau',
  'Zwiesel', 'Zwingenberg', 'Zwickau'
];

// Export: eindeutige Städte (Reihenfolge der ersten Vorkommen bleibt erhalten)
export const cities: string[] = Array.from(new Set(rawCities));

